//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap breakerTitile {
            get {
                object obj = ResourceManager.GetObject("breakerTitile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;136&lt;/X&gt;
        ///    &lt;Y&gt;111&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;50&lt;/X&gt;
        ///    &lt;Y&gt;111&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;222&lt;/X&gt;
        ///    &lt;Y&gt;39&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;184&lt;/X&gt;
        ///    &lt;Y&gt;75&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;12&lt;/X&gt;
        ///    &lt;Y&gt;75&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;98&lt;/X&gt;
        ///    &lt;Y&gt;75&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;136&lt;/X&gt;
        ///    &lt;Y&gt;39&lt;/Y&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string brickTest {
            get {
                return ResourceManager.GetString("brickTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirtBlock {
            get {
                object obj = ResourceManager.GetObject("dirtBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goodBackground {
            get {
                object obj = ResourceManager.GetObject("goodBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hello {
            get {
                object obj = ResourceManager.GetObject("hello", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;533&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;219&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;963&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;275&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;533&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;327&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;....
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Minecraft {
            get {
                object obj = ResourceManager.GetObject("Minecraft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftBackground1 {
            get {
                object obj = ResourceManager.GetObject("minecraftBackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftHeart {
            get {
                object obj = ResourceManager.GetObject("minecraftHeart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftScreen {
            get {
                object obj = ResourceManager.GetObject("minecraftScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newPlainsBackground {
            get {
                object obj = ResourceManager.GetObject("newPlainsBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plainsBackground__1_ {
            get {
                object obj = ResourceManager.GetObject("plainsBackground__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
