//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap breakerTitile {
            get {
                object obj = ResourceManager.GetObject("breakerTitile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Bricks&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;136&lt;/X&gt;
        ///    &lt;Y&gt;111&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;50&lt;/X&gt;
        ///    &lt;Y&gt;111&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;222&lt;/X&gt;
        ///    &lt;Y&gt;39&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;184&lt;/X&gt;
        ///    &lt;Y&gt;75&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;12&lt;/X&gt;
        ///    &lt;Y&gt;75&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;98&lt;/X&gt;
        ///    &lt;Y&gt;75&lt;/Y&gt;
        ///    &lt;HP&gt;1&lt;/HP&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;X&gt;136&lt;/X&gt;
        ///    &lt;Y&gt;39&lt;/Y&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string brickTest {
            get {
                return ResourceManager.GetString("brickTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cavesBackground {
            get {
                object obj = ResourceManager.GetObject("cavesBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cavesBackgroundDeath {
            get {
                object obj = ResourceManager.GetObject("cavesBackgroundDeath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamondBlock {
            get {
                object obj = ResourceManager.GetObject("diamondBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirtBlock {
            get {
                object obj = ResourceManager.GetObject("dirtBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap endBackground {
            get {
                object obj = ResourceManager.GetObject("endBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap endBackgroundDeath {
            get {
                object obj = ResourceManager.GetObject("endBackgroundDeath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goodBackground {
            get {
                object obj = ResourceManager.GetObject("goodBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goodBackgroundDeath {
            get {
                object obj = ResourceManager.GetObject("goodBackgroundDeath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hello {
            get {
                object obj = ResourceManager.GetObject("hello", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ironBlock {
            get {
                object obj = ResourceManager.GetObject("ironBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;533&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;219&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;963&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;275&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;533&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;327&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;....
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;1288&lt;/X&gt;&lt;Y&gt;147&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1288&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;361&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;963&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;361&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;963&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;399&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;363&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;791&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;791&lt;/X&gt;&lt;Y&gt;219&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&g....
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;877&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;447&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1288&lt;/X&gt;&lt;Y&gt;147&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1288&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;447&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;619&lt;/X&gt;&lt;Y&gt;219&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;705&lt;/X&gt;&lt;Y&gt;183&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;533&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;791&lt;/X&gt;&lt;Y&gt;219&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;791&lt;/X&gt;&lt;Y&gt;147&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&g....
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;403&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;919&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;403&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;919&lt;/X&gt;&lt;Y&gt;291&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;661&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;489&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;833&lt;/X&gt;&lt;Y&gt;255&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;575&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;661&lt;/X&gt;&lt;Y&gt;147&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;489&lt;/X&gt;&lt;Y&gt;147&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;....
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;357&lt;/X&gt;&lt;Y&gt;579&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;357&lt;/X&gt;&lt;Y&gt;435&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;959&lt;/X&gt;&lt;Y&gt;579&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;959&lt;/X&gt;&lt;Y&gt;435&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;152&lt;/X&gt;&lt;Y&gt;471&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1168&lt;/X&gt;&lt;Y&gt;471&lt;/Y&gt;&lt;HP&gt;4&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;152&lt;/X&gt;&lt;Y&gt;507&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1168&lt;/X&gt;&lt;Y&gt;507&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;357&lt;/X&gt;&lt;Y&gt;615&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;959&lt;/X&gt;&lt;Y&gt;615&lt;/Y&gt;&lt;HP&gt;2&lt;/HP&gt;&lt;/brick&gt;&lt;brick&g....
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;55&lt;/X&gt;&lt;Y&gt;419&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;55&lt;/X&gt;&lt;Y&gt;455&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1256&lt;/X&gt;&lt;Y&gt;419&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1256&lt;/X&gt;&lt;Y&gt;455&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;657&lt;/X&gt;&lt;Y&gt;455&lt;/Y&gt;&lt;HP&gt;5&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;571&lt;/X&gt;&lt;Y&gt;491&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;657&lt;/X&gt;&lt;Y&gt;491&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;743&lt;/X&gt;&lt;Y&gt;491&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;1084&lt;/X&gt;&lt;Y&gt;491&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;227&lt;/X&gt;&lt;Y&gt;491&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt....
        /// </summary>
        internal static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;977&lt;/X&gt;&lt;Y&gt;459&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;805&lt;/X&gt;&lt;Y&gt;459&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;284&lt;/X&gt;&lt;Y&gt;459&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;370&lt;/X&gt;&lt;Y&gt;459&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;456&lt;/X&gt;&lt;Y&gt;459&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;891&lt;/X&gt;&lt;Y&gt;459&lt;/Y&gt;&lt;HP&gt;3&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;412&lt;/X&gt;&lt;Y&gt;423&lt;/Y&gt;&lt;HP&gt;5&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;326&lt;/X&gt;&lt;Y&gt;423&lt;/Y&gt;&lt;HP&gt;5&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;370&lt;/X&gt;&lt;Y&gt;387&lt;/Y&gt;&lt;HP&gt;5&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;891&lt;/X&gt;&lt;Y&gt;387&lt;/Y&gt;&lt;HP&gt;5&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;....
        /// </summary>
        internal static string level7 {
            get {
                return ResourceManager.GetString("level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Minecraft {
            get {
                object obj = ResourceManager.GetObject("Minecraft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftBackground1 {
            get {
                object obj = ResourceManager.GetObject("minecraftBackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftHeart {
            get {
                object obj = ResourceManager.GetObject("minecraftHeart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraftScreen {
            get {
                object obj = ResourceManager.GetObject("minecraftScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherBackground {
            get {
                object obj = ResourceManager.GetObject("netherBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherBackgroundDeath {
            get {
                object obj = ResourceManager.GetObject("netherBackgroundDeath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netherrackBlock {
            get {
                object obj = ResourceManager.GetObject("netherrackBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newPlainsBackground {
            get {
                object obj = ResourceManager.GetObject("newPlainsBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obsidianBlock {
            get {
                object obj = ResourceManager.GetObject("obsidianBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plainsBackground__1_ {
            get {
                object obj = ResourceManager.GetObject("plainsBackground__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stoneBlock {
            get {
                object obj = ResourceManager.GetObject("stoneBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transitionScreen {
            get {
                object obj = ResourceManager.GetObject("transitionScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warpedForestBackground {
            get {
                object obj = ResourceManager.GetObject("warpedForestBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warpedForestBackgroundDeath {
            get {
                object obj = ResourceManager.GetObject("warpedForestBackgroundDeath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
