//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap breakerTitile {
            get {
                object obj = ResourceManager.GetObject("breakerTitile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Bricks&gt;&lt;brick&gt;&lt;X&gt;136&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;50&lt;/X&gt;&lt;Y&gt;111&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;222&lt;/X&gt;&lt;Y&gt;39&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;184&lt;/X&gt;&lt;Y&gt;75&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;12&lt;/X&gt;&lt;Y&gt;75&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;98&lt;/X&gt;&lt;Y&gt;75&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;136&lt;/X&gt;&lt;Y&gt;39&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;50&lt;/X&gt;&lt;Y&gt;39&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;184&lt;/X&gt;&lt;Y&gt;3&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;98&lt;/X&gt;&lt;Y&gt;3&lt;/Y&gt;&lt;HP&gt;1&lt;/HP&gt;&lt;/brick&gt;&lt;brick&gt;&lt;X&gt;12&lt;....
        /// </summary>
        internal static string brickTest {
            get {
                return ResourceManager.GetString("brickTest", resourceCulture);
            }
        }
    }
}
